sqr: sqr.s
	gcc -static -o sqr sqr.s

maxarray: maxarray.s maxarray.c
	gcc -static -o maxarray maxarray.c maxarray.s

selection: selection.s
	gcc -static -g -o selection selection.c selection.s

avg: avg.s
	gcc -static -o avg avg.s

maxmin: maxmin.s
	gcc -static -g -o maxmin maxmin.s

helloCS250: helloCS250.s
	gcc -static -o helloCS250 helloCS250.s

addarray: addarray.s
	gcc -static -g -o addarray addarray.s

mem: mem.c
	gcc -g -o mem mem.c

prints: prints.s
	gcc -static -g -o prints prints.s

rangeArray: rangeArray.s
	gcc -static -g -o rangeArray rangeArray.c rangeArray.s

clean:
	rm -f sqr maxarray selection avg

	
